---
#two two containers in a single pod
apiVersion: v1
kind: Pod
metadata:
  name: testpod3
spec:
  containers:
  - name: main
    image: ubuntu
    command: ["/bin/bash", "-c", "while true; do echo Hello-Adam; sleep 8 ; done"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  - name: sidecar
    image: httpd
    resources:
     limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
