---
#lable understaind ..... better
apiVersion: v1
kind: Pod
metadata:
  name: labelspod
  labels:
    name: ADAM
    org: IT
spec:
  containers:
  - name: c00
    image: ubuntu
    command: ["/bin/bash", "-c", "while true; do echo Hello-Sanjeev; sleep 5 ; done"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
   
