---
#node selector , where to run your pod, which node
apiVersion: v1
kind: Pod
metadata:
  name: nodelabes
  labels:
    name: dev
spec:
  containers:
  - name: c00
    image: ubuntu
    command: ["/bin/bash", "-c", "while true; do echo Hello-Sanjeev; sleep 5 ; done"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  nodeSelector:
     mynode: demonode

