apiVersion: v1
kind: Pod
metadata:
  name: httpdpod
  labels:
    name: httpdLabel
spec:
  containers:
    - name: httpd1
      image: httpd
      ports:
        - containerPort: 80
      resources:
       limits:
        memory: "128Mi"
        cpu: "500m"
    - name: ubuntu
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Hello-Sanjeev; sleep 8 ; done"]  #  must specify at least one command for the container
      resources:
       limits:
        memory: "128Mi"
        cpu: "500m"
      imagePullPolicy: IfNotPresent  #default is always, can keep never also.  

#$ kubectl exec microservice1 -c main -it -- /bin/bash
#$ apt update && apt install -y curl
#$ curl localhost:80
