apiVersion: v1
kind: Pod
metadata:
  name: myvol
  labels:
    name: myvolmain
spec:
  volumes:              # Definition for host
   - name: xchange
     emptyDir: {}
  name:
  containers:
  - name: main
    image: centos
    command : ["/bin/bash", "-c" ,"sleep 10000"]
    volumeMounts:
    - name: xchange
      mountPath:  "/temp/data"        # Path inside the container to share
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
