---
# deployment ojbect learning
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
spec:
  replicas : 2
  selector:
    matchLabels:
      app: deploy
  template:
    metadata:
      name: testpod
      labels:
        app: deploy
    spec:
      containers:
      - name: main
        image: ubuntu:22.10
        command: ["/bin/bash", "-c", "while true; do echo Hello-Adam; sleep 5; done"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
     
