---
# deploy httpd applications
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployhttpd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpdpod
  template:
    metadata:
      labels:
        app: httpdpod
    spec:
      containers:
      - name: wc00
        image: httpd
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
