apiVersion: v1
kind: Service
metadata:
  name: service_nodeport
spec:
  selector:
    app: httpdpod  # Apply this service to any pods which has the specific label
  ports:
  - port: 80         # Containers port exposed
    targetPort: 80   # Pods port
  type: NodePort   # it can be ClusterIP (default) or NodePort or loadbalancer/ingress ( NodePort + AWS load balancer) or headless
   # 30000 - 32767