# app1
apiVersion: v1
kind: Pod
metadata:
  name: app1
  labels:
    env: dev
spec:
  containers:
  - name: app1
    image: nginx
    resources:
      requests:
        memory: "4Gi"
        cpu: "2"
      limits:      
        memory: "4Gi"
        cpu: "2"


#$ kubectl apply -f app3.yml 
#$ kubectl get pods 
#$ kubectl describe pod app3
#$ kubectl describe pod app1 |grep -i priority
#$ kubectl describe pod app2 |grep -i priority
