---
# app2
apiVersion: v1
kind: Pod
metadata:
  name: app2
  labels:
    env: preprod
spec:
  containers:
  - name: app2
    image: nginx
    resources:
      requests:
        memory: "4Gi"
        cpu: "1"
      limits:      
        memory: "4Gi"
        cpu: "2"